services:
  wasserstrahl-kalkulator:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped
